trigger:
  branches:
    include:
      - main            # build + deploy on pushes
pr:
  branches:
    include:
      - main            # build validation on PRs
# -------- Build Environment --------
pool:
  vmImage: 'ubuntu-latest'
# -------- Variables --------
variables:
  NODE_VERSION: '18.x'
  SERVICE_CONNECTION: 'AzureStaticWebApp'
  # WARNING: For production, use Azure DevOps pipeline variables instead of hardcoding tokens
  DEPLOYMENT_TOKEN: '7a2fb256873b7c285980f0ec65261915f7428e4e801854e69b74f04c74593f3702-7c1bd93d-c543-47f3-89cd-cd3330e05c9601e280907436501e'
# -------- Steps --------
steps:
# 1. Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '$(NODE_VERSION)'
  displayName: 'Install Node.js $(NODE_VERSION)'

# 1b. SonarQube Prepare
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'SonarQubeCommunityBuild'  # Service connection name for your SonarQube server
    scannerMode: 'CLI'                    # Use standalone/CLI scanner
    configMode: 'manual'                  # Manually provide configuration
    cliProjectKey: 'mathic'               # SonarQube project key
    cliSources: '.'                       # Source directory to scan
  displayName: 'Prepare analysis on SonarQube'
# 2. Dependencies
- script: npm install
  displayName: 'npm install'
# 3. Lint
- script: npm run lint
  displayName: 'npm run lint'
# 4. Test
- script: npm run test
  displayName: 'npm run test'
# 5. Build
- script: npm run build
  displayName: 'npm run build'

# SonarQube - Run analysis
- task: SonarQubeAnalyze@5
  displayName: 'Run SonarQube analysis'

# SonarQube - Publish Quality Gate results
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'              # Wait up to 5 min for Quality Gate (optional)
  displayName: 'Publish SonarQube Quality Gate results'
# 6. Deploy (only for main branch)
- task: AzureStaticWebApp@0
  inputs:
    app_location: '/'
    output_location: '.next'
    azure_static_web_apps_api_token: $(DEPLOYMENT_TOKEN)
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  displayName: 'Deploy to Azure Static Web App'