trigger:
  branches:
    include:
      - main            # build + deploy on pushes
pr:
  branches:
    include:
      - main            # build validation on PRs
# -------- Build Environment --------
pool:
  vmImage: 'ubuntu-latest'
# -------- Variables --------
variables:
  NODE_VERSION: '18.x'
  SERVICE_CONNECTION: 'AzureStaticWebApp'
  # WARNING: For production, use Azure DevOps pipeline variables instead of hardcoding tokens
  DEPLOYMENT_TOKEN: '7a2fb256873b7c285980f0ec65261915f7428e4e801854e69b74f04c74593f3702-7c1bd93d-c543-47f3-89cd-cd3330e05c9601e280907436501e'
# -------- Steps --------
steps:
# 1. Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '$(NODE_VERSION)'
  displayName: 'Install Node.js $(NODE_VERSION)'
# 2. Dependencies
- script: npm install
  displayName: 'npm install'
# 3. Lint
- script: npm run lint
  displayName: 'npm run lint'
# 4. Test
- script: npm run test
  displayName: 'npm run test'
# 5. Build
- script: npm run build
  displayName: 'npm run build'
# 6. Detect output dir (out / .next / build / dist)
- bash: |
    set -e
    if [ -d "./out" ]; then DIR="out";
    elif [ -d "./.next" ]; then DIR=".next";
    elif [ -d "./build" ]; then DIR="build";
    elif [ -d "./dist" ]; then DIR="dist";
    else
      echo "ERROR: Unable to detect build output directory." >&2
      exit 1
    fi
    echo "Detected build output: $DIR"
    echo "##vso[task.setvariable variable=BUILD_OUTPUT_DIR]$DIR"
  displayName: 'Detect build output directory'
# 7. Deploy (only for main branch)
- task: AzureStaticWebApp@0
  inputs:
    app_location: '/'
    output_location: '$(BUILD_OUTPUT_DIR)'
    azure_static_web_apps_api_token: $(DEPLOYMENT_TOKEN)
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  displayName: 'Deploy to Azure Static Web App'
- task: AzureStaticWebApp@0
  displayName: 'Deploy to Azure Static Web App'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    azureSubscription: '$(SERVICE_CONNECTION)'
    app_location: '/'                       # repo root
    output_location: '$(BUILD_OUTPUT_DIR)'
    azureStaticWebAppsApiToken: '$(AZURE_STATIC_WEB_APPS_API_TOKEN)'  # Changed from AZURE_STATIC_WEB_APPS_API_TOKEN
    skip_app_build: true                    # we already built the app